// Generated by CoffeeScript 1.7.1
(function() {
  var CoffeeBorker;

  CoffeeBorker = (function() {
    function CoffeeBorker() {}

    CoffeeBorker.prototype.bork = function() {
      throw new Error("Bork from coffeescript");
    };

    return CoffeeBorker;

  })();

  window.coffee_bork = function() {
    return new CoffeeBorker().bork();
  };

}).call(this);

//# sourceMappingURL=bork_coffee.map
